### ISSUE TITLE
option `oneof=unions` causing error `Cannot read properties of undefined (reading 'name')`

### ISSUE THREAD

**Issue by yl2chen** [stephenh/ts-proto#480]
Using following versions:
- protoc: `3.19.1`
- ts-proto: `1.102.0`
- ts-proto-descriptors: `1.4.0`

With options:
- `--ts_proto_opt=oneof=unions`

We are seeing the following error
```
FAILED!Cannot read properties of undefined (reading 'name')TypeError: Cannot read properties of undefined (reading 'name')
    at generateOneofProperty (/usr/local/share/.config/yarn/global/node_modules/ts-proto/build/main.js:479:77)
    at /usr/local/share/.config/yarn/global/node_modules/ts-proto/build/main.js:457:29
    at Array.forEach (<anonymous>)
    at generateInterfaceDeclaration (/usr/local/share/.config/yarn/global/node_modules/ts-proto/build/main.js:451:23)
    at /usr/local/share/.config/yarn/global/node_modules/ts-proto/build/main.js:60:21
    at /usr/local/share/.config/yarn/global/node_modules/ts-proto/build/visit.js:25:9
    at Array.forEach (<anonymous>)
    at Object.visit (/usr/local/share/.config/yarn/global/node_modules/ts-proto/build/visit.js:19:14)
    at Object.generateFile (/usr/local/share/.config/yarn/global/node_modules/ts-proto/build/main.js:59:13)
    at /usr/local/share/.config/yarn/global/node_modules/ts-proto/build/plugin.js:22:37--ts_proto_out: protoc-gen-ts_proto: Plugin failed with status code 1.
```

**Comment by yl2chen** [comment]
@stephenh any help here would be greatly appreciated!

**Comment by andreasnomikos** [comment]
Thanks so much for the quick turnaround.

**Comment by yl2chen** [comment]
Great thank you!
